version: 0.2
phases:
  install:
    commands:
      - go build
      - aws cloudformation package
          --template-file sam.yaml
          --s3-bucket abn-ambro-deployment-bucket
          --output-template-file output.yaml
artifacts:
  type: zip
  files:
    - sam.yaml
    - output.yaml