version: 0.2
phases:
  pre_build:
    commands:
      - dep ensure
  build:
    commands:
      - make build
      - aws cloudformation package --template-file sam.yml --s3-bucket abn-ambro-deployment-bucket --output-template-file output.yml
artifacts:
  type: zip
  files:
    - sam.yml
    - output.yml