version: 0.2
env:
  variables:
    PACKAGE: "github.com/petrulis/abn-amro-assignment"
    BUCKET: "abn-amro-pipeline-templatebucket-ahmq4kn3umy0"
    TABLE_NAME: "MessageRequest"
phases:
  install:
    commands:
      - export GOPATH=/go
      - mkdir -p "/go/src/$(dirname ${PACKAGE})"
      - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/${PACKAGE}"
      - env
      - go get -u github.com/golang/lint/golint
  pre_build:
    commands:
      - cd "/go/src/${PACKAGE}"
      - dep ensure
      - golint -set_exit_status
  build:
    commands:
      - make build
      - aws cloudformation package --template-file sam.yml --s3-bucket ${BUCKET} --output-template-file output.yml
  post_build:
    commands:
      - printf '{"Env":"%s","TableName":"%s"}' "$ENV" "$TABLE_NAME" > params.json
      - cat params.json
artifacts:
  type: zip
  files:
    - sam.yml
    - output.yml
    - params.json